### ISSUE TITLE
Replace European Comission Logo with EU_Funded emblem

### ISSUE THREAD

**Issue by rsanz** [CoreSenseEU/.github#1]
Replace European Commission Logo with EU_Funded emblem. We cannot use the EC Logo (the Berlaymont building) and shall use the "Funded by the European Union" emblem:

https://eismea.ec.europa.eu/sites/default/files/styles/embed_large_2x/public/2022-06/eu_funded_en.jpg

**Comment by fmrico** [comment]
Fixed
